# Generated by Django 5.2.2 on 2025-06-12 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='izoh',
        ),
    ]
