# Generated by Django 5.2.2 on 2025-06-12 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_delete_commentlike'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articlelike',
            unique_together=set(),
        ),
    ]
