# Generated by Django 5.2.2 on 2025-06-15 17:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_articlelike_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articlelike',
            unique_together={('article', 'user', 'session_key')},
        ),
    ]
